### ISSUE TITLE
Reinstalling the cache fails every time

### ISSUE THREAD

**Issue by helderm** [candrews/HttpResponseCache#11]
Use Case: User wants to clear all data stored in the cache.

To achieve that, I called <code>HttpResponceCache.delete()</code>. Everything worked as expected, but I lost the http cache in the process. After trying to <code>install()</code> again, I received the following exception:

08-04 17:59:37.270: E/AndroidRuntime(328): java.lang.RuntimeException: An error occured while executing doInBackground()
...
08-04 17:59:37.270: E/AndroidRuntime(328): Caused by: java.lang.Error: Attempt to set factory more than once.
08-04 17:59:37.270: E/AndroidRuntime(328):  at java.net.URL.setURLStreamHandlerFactory(URL.java:139)
08-04 17:59:37.270: E/AndroidRuntime(328):  at com.integralblue.httpresponsecache.HttpResponseCache.install(HttpResponseCache.java:186)

**Comment by candrews** [comment]
Fixed, see c6f8eef78bbb9d2eee9e02916e39788598d627f1
