### ISSUE TITLE
Snapshot give unknown method error in Android 2.2

### ISSUE THREAD

**Issue by iNoles** [candrews/HttpResponseCache#12]
08-06 22:02:27.794: E/AndroidRuntime(312): Caused by: java.lang.NoSuchMethodError: java.lang.String.getBytes
08-06 22:02:27.794: E/AndroidRuntime(312):  at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.writeRequestHeaders(HttpEngine.java:642)
08-06 22:02:27.794: E/AndroidRuntime(312):  at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.readResponse(HttpEngine.java:803)
08-06 22:02:27.794: E/AndroidRuntime(312):  at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:286)
08-06 22:02:27.794: E/AndroidRuntime(312):  at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:180)

**Comment by candrews** [comment]
Thank you for the bug report! Fixed in commit 879405004f2ea594394b4b8f7e28fe4cb1871579
