### ISSUE TITLE
java.lang.NoSuchMethodError: java.lang.String.isEmpty on Android 2.2

### ISSUE THREAD

**Issue by tprochazka** [candrews/HttpResponseCache#15]
After upgrade code from Android 4.1 it doesn't wok on older Android:

08-13 08:00:25.909: E/AndroidRuntime(1836): Caused by: java.lang.NoSuchMethodError: java.lang.String.isEmpty
08-13 08:00:25.909: E/AndroidRuntime(1836):     at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.readHeaders(HttpEngine.java:612)
08-13 08:00:25.909: E/AndroidRuntime(1836):     at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:565)
08-13 08:00:25.909: E/AndroidRuntime(1836):     at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.readResponse(HttpEngine.java:817)
08-13 08:00:25.909: E/AndroidRuntime(1836):     at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:286)
08-13 08:00:25.909: E/AndroidRuntime(1836):     at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:498)

**Comment by candrews** [comment]
I was using a few methods that were introduced in Java 1.6. I removed those and restored Java 1.5 compatibility, and added a Maven plugin to ensure that I never accidentally depend on anything beyond Java 1.5 again.

I'll release a new version of the library later (probably this evening) with these fixes.
