### ISSUE TITLE
Failed to cache data on 3.0 Honeycomb

### ISSUE THREAD

**Issue by MazizEsa** [candrews/HttpResponseCache#16]
08-13 23:27:18.365: E/ConnectionManagement(422): Error found: java.net.ConnectException: /192.168.0.101:8888 - Connection refused
08-13 23:27:18.365: E/ConnectionManagement(422):    at org.apache.harmony.luni.net.PlainSocketImpl.connect(PlainSocketImpl.java:211)
08-13 23:27:18.365: E/ConnectionManagement(422):    at org.apache.harmony.luni.net.PlainSocketImpl.connect(PlainSocketImpl.java:431)
08-13 23:27:18.365: E/ConnectionManagement(422):    at java.net.Socket.connect(Socket.java:901)
08-13 23:27:18.365: E/ConnectionManagement(422):    at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpConnection.<init>(HttpConnection.java:78)
08-13 23:27:18.365: E/ConnectionManagement(422):    at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpConnection.<init>(HttpConnection.java:51)
08-13 23:27:18.365: E/ConnectionManagement(422):    at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:359)
08-13 23:27:18.365: E/ConnectionManagement(422):    at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:80)
08-13 23:27:18.365: E/ConnectionManagement(422):    at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpConnection.connect(HttpConnection.java:129)
08-13 23:27:18.365: E/ConnectionManagement(422):    at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:313)
08-13 23:27:18.365: E/ConnectionManagement(422):    at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.connect(HttpEngine.java:308)
08-13 23:27:18.365: E/ConnectionManagement(422):    at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:287)
08-13 23:27:18.365: E/ConnectionManagement(422):    at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:237)
08-13 23:27:18.365: E/ConnectionManagement(422):    at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:84)

The application already access the web page once (the page header Cache-Control is 60). Then the server is disabled within 60 second and application tries to access again. No data found and the stack trace above is produce. 
Using same library in Android 4.x, it will retrieve the page from the cache.

**Comment by MazizEsa** [comment]
Found the problem. It seems HttpUrlConnection setDoOutput() set to true is causing the problem. The library works when you set to false.

**Comment by candrews** [comment]
That doesn't make a lot of sense... from the stack trace you've provided, it appears that your device was trying to reach a server at 192.168.0.101:8888 refused the connection. So that's a network level problem, not in the software here. But, if you provide a bit of sample code which reproduces the problem, I'll be happy to try it and explore it some more.

**Comment by MazizEsa** [comment]
Hi Craig.
Thanks for the reply.
Yeah you are right. The stack trace does point to network level problem. But
when running the same code with seDoOutput() off, it will read from the
cache (if it's available) instead of trying to access the server. I'm not
sure why though.

Regards.

From:  Craig notifications@github.com
Reply-To:  candrews/HttpResponseCache
<reply+i-6196360-6d0dc01d35d6af868685d3190eaf64d0a076942d-1955327@reply.gith
ub.com>
Date:  Friday, August 31, 2012 10:52 AM
To:  candrews/HttpResponseCache HttpResponseCache@noreply.github.com
Cc:  Ahmad Maziz Esa maziz.esa@gmail.com
Subject:  Re: [HttpResponseCache] Failed to cache data on 3.0 Honeycomb
(#16)

That doesn't make a lot of sense... from the stack trace you've provided, it
appears that your device was trying to reach a server at 192.168.0.101:8888
refused the connection. So that's a network level problem, not in the
software here. But, if you provide a bit of sample code which reproduces the
problem, I'll be happy to try it and explore it some more.

 ‹
 Reply to this email directly or view it on GitHub
<https://github.com/candrews/HttpResponseCache/issues/16#issuecomment-818127
6> .
