### ISSUE TITLE
stat tracking doesn't work

### ISSUE THREAD

**Issue by candrews** [candrews/HttpResponseCache#2]
We're installing an android.net.http.HttpResponseCache, but libcore's HttpEngine uses 'instanceof libcore.net.http.HttpResponseCache' to guard calls to the trackResponse() methods. So stats tracking isn't working for HTTP response caches installed through the documented API.

It worked in the tests because they don't use the android.net wrapper. Ugh.

See https://code.google.com/p/android/issues/detail?id=25418

**Comment by candrews** [comment]
Fixed - 1047f29861a8cbb6eb60ef53c2a56f836ce377a1

**Comment by schmich** [comment]
I hit this issue as well using the 1.0.0 released binary. Would it be possible to get an incremental release/JAR that includes this fix? If not, I'll get the source and build it myself.

Thanks for doing all of this work to enable this on downlevel Android.
