### ISSUE TITLE
Handling Temporary Redirects (Http Response Code: 307)

### ISSUE THREAD

**Issue by MazizEsa** [candrews/HttpResponseCache#21]
This happen when using HTTPResponseCache on a site that redirects to other address. The site will return code 307 and will provide Location parameter in the header.

When this happens, the following stack trace will be displayed:
09-21 10:47:47.846: E/ConnectionManagement(1532): Error found: java.net.SocketTimeoutException: failed to connect to abcd.efgh.com/12.923.211.34 (port 80) after 60000ms
09-21 10:47:47.846: E/ConnectionManagement(1532):   at libcore.io.IoBridge.connectErrno(IoBridge.java:150)
09-21 10:47:47.846: E/ConnectionManagement(1532):   at libcore.io.IoBridge.connect(IoBridge.java:112)
09-21 10:47:47.846: E/ConnectionManagement(1532):   at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
09-21 10:47:47.846: E/ConnectionManagement(1532):   at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
09-21 10:47:47.846: E/ConnectionManagement(1532):   at java.net.Socket.connect(Socket.java:842)
09-21 10:47:47.846: E/ConnectionManagement(1532):   at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpConnection.<init>(HttpConnection.java:78)
09-21 10:47:47.846: E/ConnectionManagement(1532):   at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpConnection.<init>(HttpConnection.java:51)
09-21 10:47:47.846: E/ConnectionManagement(1532):   at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:359)
09-21 10:47:47.846: E/ConnectionManagement(1532):   at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:80)
09-21 10:47:47.846: E/ConnectionManagement(1532):   at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpConnection.connect(HttpConnection.java:129)
09-21 10:47:47.846: E/ConnectionManagement(1532):   at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:313)
09-21 10:47:47.846: E/ConnectionManagement(1532):   at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.connect(HttpEngine.java:308)
09-21 10:47:47.846: E/ConnectionManagement(1532):   at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:287)
09-21 10:47:47.846: E/ConnectionManagement(1532):   at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:237)

**Comment by candrews** [comment]
It looks like the redirect destination resulting in a time out:
Error found: java.net.SocketTimeoutException: failed to connect to abcd.efgh.com/12.923.211.34 (port 80) after 60000ms

If you believe my assessment is incorrect, please reopen the issue and let me know what I'm missing.
