### ISSUE TITLE
java.lang.NoSuchMethodError: Llibcore/net/http/HttpResponseCache.getCache 

### ISSUE THREAD

**Issue by lkorth** [candrews/HttpResponseCache#27]
When executing 

``` java
 HttpResponseCache.install(new File(context.getCacheDir(), "http"), size * 1024 * 1024);
```

I get a java.lang.NoSuchMethodError: Llibcore/net/http/HttpResponseCache.getCache error. The stack trace is pointing to 

``` java
DiskLruCache installedCache = installed.delegate.getCache();
```

in the install method in HttpResponseCache.

I'm having the problem on Android 4.2, I haven't tested it on other versions yet

**Comment by candrews** [comment]
Are you using the jar provided by me, or building HttpResponseCache yourself?

This error occurs if you build using Ant or something like that, or copying the HttpResponseCache code into your application and expect it to work. You need to install it as documented in the README.md.

**Comment by candrews** [comment]
Are you using the jar provided by me, or building HttpResponseCache yourself?

This error occurs if you build using Ant or something like that, or copying the HttpResponseCache code into your application and expect it to work. You need to install it as documented in the README.md.

**Comment by lkorth** [comment]
I was building it myself, guess I'll be switching to using jars (or maybe this is an excuse to learn maven).

Now if only github's file server would come back online and comments weren't broken...
