### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by sihut** [candrews/HttpResponseCache#4]
I use the HttpResponseCache for several weeks now. Since today I get the following error when istalling the cache with "com.integralblue.httpresponsecache.HttpResponseCache.install(httpCacheDir, httpCacheSize)":

W/dalvikvm(14655): VFY: unable to resolve static method 11: Lcom/integralblue/httpresponsecache/HttpResponseCache;.install (Ljava/io/File;J)Lcom/integralblue/httpresponsecache/HttpResponseCache;
W/dalvikvm(14655): threadid=1: thread exiting with uncaught exception (group=0x40020ac0)
E/AndroidRuntime(14655): FATAL EXCEPTION: main
E/AndroidRuntime(14655): java.lang.NoClassDefFoundError: com.integralblue.httpresponsecache.HttpResponseCache

The error occurs on Android 2.2. The source code ist unaltered I did not change anything. The only things I did, I updated some components of the Android SDK and the ADT plugin (now v. 17.0.0).

**Comment by candrews** [comment]
If you're using proguard, check your proguard configuration.
If not, make sure you do a full clean.

As the error states, the class com.integralblue.httpresponsecache.HttpResponseCache isn't being resolved. There's not much I can do for you - it's not a bug in the library.

**Comment by mikebevz** [comment]
Same issue here. Updated ADT to v.17 and having this problem. Any ideas, solutions?
