### ISSUE TITLE
Pull file writing optimization

### ISSUE THREAD

**Issue by swankjesse** [candrews/HttpResponseCache#9]
You should grab this optimization from upstream Android
https://android-review.googlesource.com/#/c/38884/

**Comment by jaypatrickhoward** [comment]
Applying this patched solved my performance issues noted in issue #7.  Unfortunately, it means my app needs to default to using the patched candrews HttpResponseCache instead of the one that ships with ICS, since the one that ships with ICS isn't patched.

**Comment by candrews** [comment]
Included in ec2b98aed81af1145ebad527fe96bbaae323de0c - thank you!
